In [2]:
import pandas as pd
data = {
    'Name': ["Alice","Bob","Charlie"],
    'Age': [25,30,35]
}
s = pd.DataFrame(data)
s

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [2]:
import pandas as pd
data = {
'Student': ['Ali', 'Zain', 'Sara'],
'GPA': [3.8, 3.2, 3.9],
'City': ['Lahore', 'Karachi', 'Islamabad']
}
df = pd.DataFrame(data)
df

  Student  GPA       City
0     Ali  3.8     Lahore
1    Zain  3.2    Karachi
2    Sara  3.9  Islamabad